const swaggerAutogen = require('swagger-autogen')()
require("dotenv").config();


const doc = {
    info: {
        version: "1.0.0",
        title: "Integration of weather forecast data",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: process.env.IP_ADDRESS + ":" + process.env.PORT,
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [{
        "name": "Weather Forecast",
        "description": "Endpoints"
    }],
    securityDefinitions: {
        AUTHORIZATION: {
            type: "apiKey",
            name: "AUTHORIZATION",
            in: "header",
            description: "Enter JWT Bearer token **_only_**",
            scheme: "bearer",
            bearerFormat: "JWT"
        },
        security: [
            {
                AUTHORIZATION: []
            }
        ],
        petstore_auth: {
            type: "oauth2",
            authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
            flow: "implicit",
            scopes: {
                read_pets: "read your pets",
                write_pets: "modify pets in your account"
            }
        }
    },
    definitions: {     
            generateToken: {
                username: "",
                password: ""
            }
        }

}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./index.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index') // Your project's root file
})